[versions]
jetty = "9.4.30.v20200611"
junit = "5.6.2"

[libraries]
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty" }

guava = { module = "com.google.guava:guava", version = "29.0-jre" }

httpclient = { module = "org.apache.httpcomponents:httpclient", version = "4.5.12" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# Gradle plugin dependencies
gradlex-jvm-dependency-conflict-resolution = { module = "org.gradlex:jvm-dependency-conflict-resolution", version = "2.1.1"}
